### PR TITLE
Changed version in demo

### PR DESCRIPTION
**Pull request by tnViking**

### CODE REVIEW

**Comment by chinchang** [comment]
Thanks!

**Comment by tnViking** [comment]
Maybe update in your website too?
http://kushagragour.in/lab/hint/

**Comment by chinchang** [comment]
Actually I realized after merging your PR that it was meant to be kept as 2.0 :) Representing the next edition of the library (2.x) that came after 1.x :)

**Comment by tnViking** [comment]
Ah, yeah I understand.

**Pull request merged**
